# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set workdir
WORKDIR /app

# Copy project files
COPY pyproject.toml README.md uv.lock /app/
COPY src /app/src

# Install dependencies
RUN pip install --no-cache-dir .

# Ensure unbuffered output
ENV PYTHONUNBUFFERED=1

# Default entrypoint
ENTRYPOINT ["todoist-mcp"]
